production:
  server: "https://dreammachine-faye.herokuapp.com/faye"

# this is the address of this heroku app once deployed plus the '/faye extension.
  secret_token: "d366571eaa2e36267e773fe73034d1ea71cf7b6ebd8e836fd7b6db143c132d43"
  signature_expiration: 3600 # one day
